### ISSUE TITLE
Amon agent installation script missing -y flag for yum

### ISSUE THREAD

**Issue by kevinquinnyo** [martinrusev/amon-issues#21]
I believe the problem is here:

```
$sudo_cmd yum install epel-release
```

Should have the `-y` so we don't have to pipe `yes` to the command.

amon version:
Amon 3.6.8

**Comment by martinrusev** [comment]
Hi @kevinquinnyo, Thanks for reporting this. I will push a bug fix release first thing in the morning( I am in UTC +3)

**Comment by martinrusev** [comment]
Hi @kevinquinnyo, This is fixed in the latest release 3.8.7
