### ISSUE TITLE
Cannot configure amon to start on boot 

### ISSUE THREAD

**Issue by clayreimann** [martinrusev/amon-issues#26]
I'm running `amon` on Cent 7 and can't get it to restart when I bounce the server. I get the following output from `chkconfig`

```
amon           	0:off	1:off	2:on	3:on	4:on	5:on	6:off
amon-agent     	0:off	1:off	2:on	3:on	4:on	5:on	6:off
mongod         	0:off	1:off	2:on	3:on	4:on	5:on	6:off
```

From the logs it looks like this is happening because `amon` tries to start before `mongod` has started.

**Comment by clayreimann** [comment]
I think I've managed to fix this by moving the files in `/etc/rc.d/rc[2-5].d/S50amon` to `/etc/rc.d/rc[2-5].d/S90amon` (since `mongod` booted with `/etc/rc.d/rc[2-5].d/S85mongod`).

**Comment by martinrusev** [comment]
Hi @clayreimann, This is fixed in 4.0.1

This is something I missed in the init script.

Before:

```
### BEGIN INIT INFO
# Provides:          amon
# Required-Start:    $remote_fs $syslog -> starts at the same time like Mongo
# Required-Stop:     $remote_fs $syslog
```
Now it is: 

```
### BEGIN INIT INFO
# Provides:          amon
# Required-Start:    $all -> Starts last
# Required-Stop:     $remote_fs $syslog
```

**Comment by clayreimann** [comment]
I'm running: CentOS Linux release 7.0.1406 (Core)

**Comment by clayreimann** [comment]
Any idea when 4.0.1 will drop?

**Comment by martinrusev** [comment]
@clayreimann I've pushed it this morning. Something you can check after update:

 ```ls /etc/rc.d/rc?.d/*```

Amon should be 95, Mongo 85, if it shows something different `chkconfig amon on` to update

**Comment by clayreimann** [comment]
Cool, I don't see upgrade instructions on the Docs page. Do I just run the installer again? Do I `yum update`? What's the procedure?

**Comment by martinrusev** [comment]
@clayreimann You have to paste the bash script from your account page or download the rpm and then `rpm -Uvh amon.rpm`

**Comment by clayreimann** [comment]
I installed amon 5.x and this seems to be resolved.
